name: CI/CD Workflow

on:
  push:
    branches: [feature/*, develop, main, release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test code
        run: |
          if [[ $GITHUB_REF == refs/heads/feature/* ]]; then
            # 빌드,테스트 feature 브랜치
          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
            # feature 브랜치들을 머지, 빌드하고 테스트 develop 브랜치 
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            # 배포 브랜치
          elif [[ $GITHUB_REF == refs/heads/release ]]; then
            # 오류수정하고 빌드, 테스트하는 release 브랜치
      - name: Deploy code
        if: github.ref == 'refs/heads/main'
        run: |
          
